services:
  db:
    image: postgres:latest
    container_name: bitrix_demo_db
    env_file:
      - ./envs/db.env
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - bitrix_demo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  fpm:
    image: php:8.2-fpm
    container_name: bitrix_demo_fpm
    networks:
      - bitrix_demo_network
    depends_on:
      - db
    volumes:
      - ./infrastructure/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./infrastructure/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./infrastructure/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./bitrix:/var/www/bitrix/bitrix
      - ./upload:/var/www/bitrix/upload
      - ./local:/var/www/bitrix/local
      - ./index.php:/var/www/bitrix/index.php
    healthcheck:
      test: ["CMD-SHELL", "php -v"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: bitrix_demo_nginx
    networks:
      - bitrix_demo_network
    depends_on:
      - fpm
    volumes:
      - ./infrastructure/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./infrastructure/var/log/nginx:/var/log/nginx
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      
networks:
  bitrix_demo_network:
    external: true
